---
- name: Установка nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Создание страницы приветсвия
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Запуск nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
