
---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    nginx:  # Имя подгруппы хостов
      hosts:  # Узлы группы
        ubuntu_nginx1:  # Имя машины
          ansible_host: 89.169.151.105  # Адрес машины
        ubuntu_nginx2:  # Имя машины
          ansible_host: 51.250.83.169  # Адрес машины
    proxy:
      hosts:  # Узлы группы
        ubuntu_proxy:  # Имя машины
          ansible_host: 46.21.246.81  # Адрес машины
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "terauser"
    ansible_ssh_private_key_file: /home/laroan/.ssh/terakey
